version: '3.9'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://cwtestcaseuser:cwtestcasepwd@db:5432/cwtestcase
    volumes:
      - .:/code
    command: >
      sh -c "python app/core/management/wait_for_db.py &&
             uvicorn app.main:app --host 0.0.0.0 --port 8000"

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: cwtestcaseuser
      POSTGRES_PASSWORD: cwtestcasepwd
      POSTGRES_DB: cwtestcase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
