version: '3.9'

services:
  app:
    build: .
    environment:
      DATABASE_URL: postgres://cwtestcaseuser:cwtestcasepwd@db:5432/cwtestcase
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    command: >
      sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000"